# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Automaducks
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima

# theme: just-the-docs
# color_scheme: dark

plugins:
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#
# Theme Values
#
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Automaducks"
title_separator          : "-"
subtitle                 : "FTC 23206"
name                     : &name "Automaducks" # &name is a YAML anchor which can be *referenced later
description              : &description "Site description"
url                      : https://www.automaducks.com
baseurl                  : ""
repository               : ""
teaser                   : ""
logo                     : /assets/images/favicon-56x56.png
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : false

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  #avatar           : "/assets/images/michael-rose.jpg"
  #bio              : "Just another *boring*, *tattooed*, *time traveling*, *designer*."
  #location         : "Buffalo, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FTC-23206"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/automaducks/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@automaducks"
    - label: "Thingiverse"
      icon: "fas fa-fw fa-link"
      url: "https://www.thingiverse.com/ftc23206/designs"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FTC-23206"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/automaducks/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@automaducks"
    - label: "Thingiverse"
      icon: "fas fa-fw fa-link"
      url: "https://www.thingiverse.com/ftc23206/designs"

# Collections
collections:
  pond:
    output: true
    permalink: /:collection/:path/
  designs:
    output: true
    permalink: /:collection/:path/

# Reading Files
include:
  - _pages
  - images

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _designs
  - scope:
      path: ""
      type: designs
    values:
      layout: single
      share: true
      author_profile: true
  # _pond
  - scope:
      path: ""
      type: pond
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "pond"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

# Analytics
analytics:
provider               : "google" # false (default), "google", "google-universal", "google-gtag", "custom"
google:
  tracking_id          : G-KYNFY6ZF6J
  anonymize_ip         : false